#!/usr/bin/python3

from sys import argv


def factorize(data):
    x = 2

    if data < 2:
        return

    while x <= data:
        if data % x == 0:
            print("{}={}*{}".format(data, data // x, x))
            break
        x += 1


if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        for line in file:
            data = int(line.strip())
            factorize(data)
except FileNotFoundError:
    print("File not found.")


