#!/usr/bin/python3

from sys import argv


def factorize(data):
    x = 2

    if data < 2:
        return
    print()
    print(data, "data")
    while x <= data:
        if data % x == 0:
            print("{:.0f}={:.0f}*{:.0f}".format(data, data / x, x))
            break
        x += 1
    print(data, "data")
    print()


if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        size = file.readline()

        while size != "":
            data = int(size.split('\n')[0])
            factorize(data)

            size = file.readline()
except FileNotFoundError:
    print("File not found.")

