#!/usr/bin/python3

import sys


def factorize(data):
    x = 2

    if data < 2:
        return

    while x * x <= data:
        if data % x == 0:
            print("{}={}*{}".format(data, data // x, x))
            return
        x += 1

    print("{}={}*{}".format(data, data, 1))


if len(sys.argv) != 2:
    sys.exit("Usage: factors <file>")

try:
    with open(sys.argv[1]) as file:
        for line in file:
            data = int(line.strip())
            factorize(data)
except FileNotFoundError:
    sys.exit("File not found.")


